image:
  - Visual Studio 2019

environment:
  matrix:
    - PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
      CONFIGURE_HOST: x86_64-w64-mingw32
      CONFIGURE_OPTS: --disable-static
    - PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
      CONFIGURE_HOST: x86_64-w64-mingw32
      CONFIGURE_OPTS: --disable-shared
    - PATH: C:\msys64\mingw32\bin;C:\msys64\usr\bin
      CONFIGURE_HOST: i686-w64-mingw32
      CONFIGURE_OPTS: --disable-static
    - PATH: C:\msys64\mingw32\bin;C:\msys64\usr\bin
      CONFIGURE_HOST: i686-w64-mingw32
      CONFIGURE_OPTS: --disable-shared

install:
  - cmd: pacman -S --noconfirm autoconf automake libtool

build:
  parallel: true

build_script:
  - cmd: bash -e ./ci/build.sh

on_success:
  - python3 ci/appveyor_irc-notify.py mcfproj "* lh_mouse {repo_name}#{short_commit} passed on {branch} ({build_url})"

on_failure:
  - python3 ci/appveyor_irc-notify.py mcfproj "* lh_mouse {repo_name}#{short_commit} errored on {branch} ({build_url})"
