image:
  - Visual Studio 2019

environment:
  matrix:
    - PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
      CXX: x86_64-w64-mingw32-g++
      CONFIGURE_OPTIONS: --disable-static
    - PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
      CXX: x86_64-w64-mingw32-g++
      CONFIGURE_OPTIONS: --disable-shared
    - PATH: C:\msys64\mingw32\bin;C:\msys64\usr\bin
      CXX: i686-w64-mingw32-g++
      CONFIGURE_OPTIONS: --disable-static
    - PATH: C:\msys64\mingw32\bin;C:\msys64\usr\bin
      CXX: i686-w64-mingw32-g++
      CONFIGURE_OPTIONS: --disable-shared

install:
  - cmd: pacman -S --noconfirm autoconf automake libtool make mingw-w64-{x86_64,i686}-gcc

build:
  parallel: true

build_script:
  - cmd: bash -e ./ci/build.sh

on_success:
  - python3 ci/appveyor_irc-notify.py mcfproj "* lh_mouse {repo_name}#{short_commit} passed on {branch} ({build_url})"

on_failure:
  - python3 ci/appveyor_irc-notify.py mcfproj "* lh_mouse {repo_name}#{short_commit} errored on {branch} ({build_url})"
